### ISSUE TITLE
"undefined" errors

### ISSUE THREAD

**Issue by garrison** [zenhack/docker-spk#15]
Hi Ian,

If I clone this repository and then run `go build`, I get a few `undefined` errors regarding `zenhack.net/go/sandstorm/exp/spk`.  To make sure it's not just something about my system, I was able to reproduce this error in the `golang:latest` Docker container:

```
root@4bcb8d9b7641:/go/docker-spk# go build
go: downloading zenhack.net/go/sandstorm v0.0.0-20200724231323-be1af19658ec
go: downloading zombiezen.com/go/capnproto2 v2.17.1-0.20180404044107-e89f9b7f0213+incompatible
go: downloading github.com/ulikunitz/xz v0.5.7
go: downloading golang.org/x/crypto v0.0.0-20200709230013-948cd5f35899
# zenhack.net/go/docker-spk
./init.go:12:17: undefined: "zenhack.net/go/sandstorm/exp/spk".NewApp
./metadata.go:21:17: undefined: "zenhack.net/go/sandstorm/exp/spk".ReadPackageDefinition
```

and no `docker-spk` output file results.

**Comment by zenhack** [comment]
Thanks for the report, looks like I forgot to update the dependencies after moving some of the code into a library. Pushed a fix to master, let me know if that addresses the issue.

**Comment by garrison** [comment]
Works now, thanks!
