### ISSUE TITLE
Path to sandstorm keyring

### ISSUE THREAD

**Issue by JamborJan** [zenhack/docker-spk#8]
The path to the sandstorm keyring is set to `/Users/{$user}/.sandstorm-keyring` by default (example from macOS). But according to my experience it should be `/Users/{$user}/.sandstorm/sandstorm-keyring`. The `spk` command and also `vagrant-spk` are using this path too.

**Comment by zenhack** [comment]
There's actually disagreement between `spk` and `vagrant-spk` here:

```
$ spk --help

    -k<path>, --keyring=<path>
        Use <path> as the keyring file, rather than $HOME/.sandstorm-keyring.
```

vs vagrant-spk, which does as you describe. Looks like the latter was added later to deal with sharing folders with the vm:

https://github.com/sandstorm-io/vagrant-spk/blob/master/vagrant-spk#L384-L387

I decided to do what `spk` does, but I don't feel strongly about that. Given that most of the developer docs are for `vagrant-spk` the latter might be more familiar to more people. Open to changing it if you feel strongly.
